robot_name_cn: '元夕'
first_name: '老板'
last_name: '李'
timezone: HKT
location: '苏州'

# 后台管理端
server:
    enable: true
    host: '0.0.0.0'  # ip 地址
    port: '5000'     # 端口号    
    username: 'yuanxi'  # 用户名
    # cookie 的 secret ，用于对 cookie 的内容进行加密及防止篡改
    # 建议使用 os.urandom(24) 生成一串随机字符串
    # 强烈建议修改!!!
    cookie_secret: '__GENERATE_YOUR_OWN_RANDOM_VALUE_HERE__'
    # 密码的 md5，可以用 python3 ros.py md5 "密码" 获得
    # 初始密码为 yuanxi@2019
    # 强烈建议修改!!!
    validate: 'b2f800a7ddd5fd5fe81a370e1b2f55d3'

# Muse 脑机
# 推荐搭配 Muse Monitor 使用
# 并开启 OSC stream
# 同时眨眼和咬牙齿可以实现唤醒
muse:
    enable: false
    ip: '0.0.0.0'  # 请修改为本机的 ip 地址
    port: 5001     # 请修改为 OSC 的端口号

# 是否展示灯光效果
# 支持 Respeaker 2 Mics 和 Google AIY Voice Kit 两种
# 必须具备相应的硬件和驱动
LED:
    enable: false
    type: aiy  # aiy: Google AIY Voice Kit; respeaker：respeaker 2Mics

# snowboy 离线唤醒
# https://snowboy.kitt.ai/dashboard
# 建议到 https://snowboy.kitt.ai/hotword/32768
# 使用相同环境录入你的语音，以提升唤醒成功率和准确率
hotword: 'yuanxi.pmdl'  # 唤醒词模型，如要自定义请放到 $HOME/.ros 目录中
sensitivity: 0.4  # 灵敏度
silent_threshold: 15 # 判断为静音的阈值。环境比较吵杂的地方可以适当调大
recording_timeout: 5 # 录制的语音最大长度（秒）
snowboy_token: your_token # 你的token，用于 train 命令训练语音

# 当机器人反问用户时，是否自动进入下一轮聆听
active_mode: true

# 勿扰模式，该时间段内自动进入睡眠，避免监听
do_not_bother:
    enable: false # true: 开启; false: 关闭
    since: 23    # 开始时间
    till: 9      # 结束时间，如果比 since 小表示第二天
    hotword_switch: false  # 是否使用唤醒词开关唤醒模式
    on_hotword: '元夕别吵.pmdl'  # 通过这个唤醒词可切换勿扰模式。默认是“元夕别吵”
    off_hotword: '元夕醒醒.pmdl'  # 通过这个唤醒词可切换勿扰模式。默认是“元夕醒醒”

# 是否定期清理temp目录下的缓存音频
lru_cache:
    enable: true # true: 开启; false: 关闭
    days: 7 # 清理超过多少天没有使用的文件

# 语音合成服务配置
# 可选值：
# han-tts       - HanTTS
# baidu-tts     - 百度语音合成（推荐）
# xunfei-tts    - 讯飞语音合成
# ali-tts       - 阿里语音合成（推荐）
# tencent-tts   - 腾讯云语音合成（推荐）
tts_engine: baidu-tts

# 语音识别服务配置
# 可选值：
# baidu-asr     - 百度在线语音识别
# xunfei-asr    - 讯飞语音识别
# ali-asr       - 阿里语音识别
# tencent-asr   - 腾讯云语音识别（推荐）
asr_engine: baidu-asr

# 百度语音服务
# http://yuyin.baidu.com/
baidu_yuyin:
    appid: ''  # 请使用自己的百度语音账户 APPID
    api_key: ''
    secret_key: ''
    dev_pid: 1936   # 1936: 普通话远场，1536：普通话(支持简单的英文识别)，80001：ASR极速版（请使用自己的百度语音账户再使用）
    per: 1  # 发音人选择 0：女生；1：男生；3：度逍遥；4：度丫丫
    lan: 'zh'


# 讯飞语音服务
# appid 及 api_key 需前往
# https://xfyun.cn/
# 注册创建是WebAPI应用，并赋予流式语音听写及在线语音合成两项能力
xunfei_yuyin:
    appid: ''
    api_key: ''  # 语音听写
    api_secret: ''
    voice: ''  # 全部可选：https://console.xfyun.cn/services/tts

# 阿里云语音
# appKey及token需前往
# https://ai.aliyun.com/nls
# 注册获取
ali_yuyin:
    appKey: ''
    token: ''
    voice: '' #xiaoyun为女生，xiaogang为男生, 全部可选：http://suo.im/4x8RzQ

# 腾讯云语音
# 先前往 https://cloud.tencent.com
# 注册语音识别和语音合成服务，获得 appid ，然后在访问管理
# https://console.cloud.tencent.com/cam
# 创建子用户，访问API密钥获得 secretid 和 secret_key
# 注册获取
tencent_yuyin:
    appid: ''
    secretid: ''
    secret_key: ''
    region: ''  # 服务地区，有效值：http://suo.im/4EEQYD
    voiceType: 0            # 0: 女声1；1：男生1；2：男生2
    language: 1             # 1: 中文；2：英文

# HanTTS 服务
han-tts:
    # 所使用的语音库目录
    # 需放在 ~/.ros/ 目录下
    # 也支持自行录制，详见：
    # https://github.com/junzew/HanTTS
    voice: 'syllables' 

# NLU 引擎
# 可选值：
# unit      - 百度 UNIT
nlu_engine: unit

# 聊天机器人
# 可选值：
# anyq      - AnyQ（推荐）
# tuling    - 图灵机器人
# emotibot  - 小影机器人
robot: emotibot

# AnyQ 机器人
anyq:
    host: 0.0.0.0
    port: 8999
    solr_port: 8900  # solr 的端口号
    # 置信度（confidence）需达到的阈值，
    # 达不到就认为不命中
    threshold: 0.6
    # 如果没有命中，使用其他兜底的机器人
    # 如果不想使用兜底，可以设为 null
    secondary: tuling

# 图灵机器人	
# http://www.tuling123.com
tuling:
    tuling_key: ''  # 建议使用自己的图灵机器人API Key

# 小影机器人
# http://botfactory.emotibot.com/
emotibot:
    appid: ''

# 邮箱
# 如果使用网易邮箱，还需设置允许第三方客户端收发邮件
email:
    enable: true
    address: '你的邮箱地址'
    password: '你的邮箱密码'  # 如果是网易邮箱，须填写应用授权密码而不是登录密码！
    smtp_server: 'smtp.163.com'
    smtp_port: '25'  # 这里填写非SSL协议端口号
    imap_server: 'imap.163.com'
    imap_port: '143'  # 这里填写非SSL协议端口号    
    read_email_title: true  # 当有邮件时，是否朗读邮件标题

# 拍照
# 需接入摄像头才能使用
camera:
    enable: false
    type: 0                 # 摄像头类型 0：usb_camera，1：树莓派 5MP 摄像头，2：Mac OSX 摄像头
                            # 对于 Mac OSX 摄像头，请先安装 imagesnap 。例如 Mac OSX： brew install imagesnap
    dest_path: "/Users/Pictures/" # 保存目录
    quality: 5              # 成像质量（0~100），不支持 imagesnap
    vertical_flip: true     # 竖直翻转，不支持 imagesnap
    horizontal_flip: false  # 水平翻转，不支持 imagesnap
    count_down: 3           # 倒计时（秒），仅当开启倒计时时有效
    sound: true             # 是否有拍照音效
    usb_camera: false       # 是否是 USB 摄像头（已废弃，请使用 type）

## 本地音乐插件
LocalPlayer:
    path: "/Users/Music"  # 本地音乐存放路径


statistic: true # 是否开启上报

#######################
# 第三方插件的配置
#######################


# 百度FM
baidufm:
    channel: 14

# 天气
# 使用心知天气的接口
# https://www.seniverse.com/
weather:
    enable: false
    key: '心知天气 API Key'


